# Generated by Django 3.0.2 on 2020-01-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='wapp',
        ),
    ]
